import = ["/home/akhercha/.config/alacritty/catpuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13

[font.bold]
family = "terminal-font"
style = "Bold"

[font.bold_italic]
family = "terminal-font"
style = "Bold Italic"

[font.italic]
family = "terminal-font"
style = "Italic"

[font.normal]
family = "terminal-font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10
